name: color_text_highlighter
description: This package makes it easy for you to select and highlight HTML with inline CSS Content. You can also add other toolbars like Select All, Delete, Search and Copy.
version: 1.0.0+3
homepage: https://github.com/rvngbrl/color_text_highlighter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  simple_html_css: ^3.0.1+1
  text_selection_controls: ^0.0.2
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

 
